# Generated by Django 4.2.11 on 2026-03-18 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CarouselImage",
        ),
    ]
