# Generated by Django 4.2.11 on 2026-04-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user',
            field=models.CharField(max_length=36),
        ),
    ]
