# Generated by Django 4.2.11 on 2026-04-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_movie_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="user",
            field=models.UUIDField(),
        ),
    ]
