# Generated by Django 4.2.11 on 2026-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
